### ISSUE TITLE
Can you add types?

### ISSUE THREAD

**Issue by weilinzung** [chrisfosterelli/akismet-api#125]
Could not find a declaration file for module 'akismet-api'. '.../node_modules/akismet-api/lib/akismet.js' implicitly has an 'any' type.
  Try `npm install @types/akismet-api` if it exists or add a new declaration (.d.ts) file containing `declare module 'akismet-api';`ts(7016)

**Comment by weilinzung** [comment]
Latest 5.0 version.

With `types.d.ts` also not work.

`declare module 'akismet-api';`

Error: Cannot find module 'akismet-api'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

**Comment by chrisfosterelli** [comment]
Thanks for opening this @weilinzung! I don't use typescript myself so I'm not likely to write up type definitions in the immediate future, but I'd accept a PR that makes life easier for typescript developers 😄 

P.S. with your particular note (not being a typescript expert), does the file name matter? i.e. `akismet-api.d.ts` vs. `types.d.ts`?

**Comment by chrisfosterelli** [comment]
@weilinzung Just noticed the issue was closed -- do you not need types anymore?

**Comment by weilinzung** [comment]
@chrisfosterelli I want it, but I just not have time to learn this plugin and write all the types.

**Comment by chrisfosterelli** [comment]
@weilinzung If you'd like to leave the issue open, someone else may be able to make a PR!

**Comment by jasonflorentino** [comment]
Hey y'all! I mentioned in the PR, but would love any feedback about it! 🙏

**Comment by chrisfosterelli** [comment]
@jasonflorentino Thanks a ton for this! I'll take a look in the next few days here

**Comment by jasonflorentino** [comment]
No prob! Hope it’s workable 😄
