### ISSUE TITLE
Add support for honeypot_field_name & hidden_honeypot_field

### ISSUE THREAD

**Issue by atido** [chrisfosterelli/akismet-api#204]
Hi,
first thank you for your great job on this client api.
Then, do you think it is possible to add support for "honeypot_field_name" & "hidden_honeypot_field", it is the only option which is present in the api Akismet and which is not present in your client. This could be useful to allow additional filtering.
Thank you in advance.

**Comment by atido** [comment]
That would be really great. This would filter spam even more effectively. For the second field "hidden_honeypot_field" in fact it is a dynamic field based on the first parameter .

Extract from the documentation:
**honeypot_field_name**
If you use a [honeypot field](https://en.wikipedia.org/wiki/Honeypot_(computing)) in your implementation, include the name of the field in your request as well as the value of that field. For example, if you have a honeypot field that looks like <input type="text" name="hidden_honeypot_field" style="display: none;" />, then you should include two extra parameters in your request: honeypot_field_name=hidden_honeypot_field and hidden_honeypot_field=[the value of the input]. 

Can't wait.
Thanks

**Comment by chrisfosterelli** [comment]
@atido I've implemented this feature and added docs about it's use here: https://github.com/chrisfosterelli/akismet-api/blob/master/docs/comments.md

Hopefully this meets your needs! I'll post here when it's live on npm as well.

**Comment by chrisfosterelli** [comment]
This is live now in [version 6.0.0](https://github.com/chrisfosterelli/akismet-api/releases/tag/v6.0.0)!

**Comment by atido** [comment]
Thank you @chrisfosterelli. Much appreciated !
