### ISSUE TITLE
is_test option

### ISSUE THREAD

**Issue by mogusbi** [chrisfosterelli/akismet-api#42]
The is_test option (https://akismet.com/development/api/#comment-check) would be very handy, especially when running integration tests on my application.

Appears easy enough to implement but would be willing to submit a pull request if required :)

**Comment by chrisfosterelli** [comment]
Thanks for the issue! I can definitely see the use case for this.
I'm open to a pull request which adds this functionality, or if you want to wait I should have time to get to this by the end of the week :)

**Comment by mogusbi** [comment]
Pull request submitted!

**Comment by chrisfosterelli** [comment]
This was resolved in #43

**Comment by chrisfosterelli** [comment]
Published in 2.2.0
