### ISSUE TITLE
submitHam and submitSpam don't send is_test property

### ISSUE THREAD

**Issue by sarvaje** [chrisfosterelli/akismet-api#65]
As well as checkSpam, submitHam and submitSpam support the property is_test so you don't need to worry about make fake submits when you are testing

**Comment by chrisfosterelli** [comment]
Thanks @sarvaje, good idea! I'll should be able to add that this weekend.

**Comment by sarvaje** [comment]
I'm going to submit a PR if you want to :)

**Comment by chrisfosterelli** [comment]
Pull requests are always welcome :)
